# Generated by Django 4.0.3 on 2026-07-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#4e79a7', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fin_categorias',
            },
        ),
        migrations.CreateModel(
            name='Finalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#59a14f', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fin_finalidades',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fin_personas',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TC', 'Tarjeta Crédito'), ('TD', 'Tarjeta Débito'), ('CB', 'Cuenta Bancaria'), ('MP', 'Mercado Pago'), ('EF', 'Efectivo')], max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.persona')),
            ],
            options={
                'db_table': 'fin_medios_pago',
            },
        ),
    ]
