# Generated by Django 4.0.3 on 2026-07-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(default='CAT', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
