# Generated by Django 4.0.3 on 2026-07-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_categoria_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalidad',
            name='color',
        ),
        migrations.AddField(
            model_name='finalidad',
            name='codigo',
            field=models.CharField(default='TMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
