# Generated by Django 4.0.3 on 2026-07-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_remove_finalidad_color_finalidad_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='codigo',
            field=models.CharField(default='TMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
