# Generated by Django 4.0.3 on 2026-07-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_persona_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediopago',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='mediopago',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='mediopago',
            name='tipo',
        ),
        migrations.AddField(
            model_name='mediopago',
            name='codigo',
            field=models.CharField(default='TMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
