# Generated by Django 4.0.3 on 2026-07-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_mediopago_options_remove_mediopago_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, unique=True)),
                ('accion', models.CharField(choices=[('C', 'Clasificar'), ('A', 'Agrupar'), ('I', 'Ignorar')], default='C', max_length=1)),
                ('grupo', models.CharField(blank=True, default='', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=200)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.categoria')),
                ('finalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.finalidad')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.persona')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'db_table': 'fin_reglas',
                'ordering': ['texto'],
            },
        ),
    ]
