# Generated by Django 4.0.3 on 2026-07-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='conciliado',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='medio_pago',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
