# Generated by Django 4.0.3 on 2026-07-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_remove_movimiento_conciliado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
