# Generated by Django 4.0.3 on 2026-07-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_alter_movimiento_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='periodo',
            field=models.CharField(db_index=True, default='', max_length=6),
            preserve_default=False,
        ),
    ]
