# Generated by Django 4.0.3 on 2026-07-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_alter_movimiento_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], default='G', max_length=1),
        ),
    ]
