# Generated by Django 4.0.3 on 2026-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_movimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='nombre_archivo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
    ]
