# Generated by Django 4.0.3 on 2026-07-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_movimiento_nombre_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='finalidad',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
