# Generated by Django 4.0.3 on 2026-07-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_alter_categoria_codigo_alter_finalidad_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='grupo_dashboard',
            field=models.CharField(choices=[('INGRESOS', 'Ingresos'), ('EGRESOS', 'Egresos'), ('TRANSFERENCIAS', 'Transferencias'), ('INVERSIONES', 'Inversiones'), ('OTROS', 'Otros')], default='EGRESOS', max_length=20),
        ),
    ]
