# Generated by Django 4.0.3 on 2026-07-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0015_categoria_grupo_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mostrar_dashboard',
            field=models.BooleanField(default=True, verbose_name='Mostrar en Dashboard'),
        ),
    ]
