# Generated by Django 4.0.3 on 2026-07-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_categoria_mostrar_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='importe_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
