# Generated by Django 4.0.3 on 2026-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionesdolar',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacionesdolar',
            name='periodo_anio',
            field=models.IntegerField(),
        ),
    ]
