# Generated by Django 4.2 on 2026-06-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0024_aseguradoras_invierte_signo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglacomision',
            name='conceptoclaro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
