# Generated by Django 4.2 on 2026-06-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0025_reglacomision_conceptoclaro'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantescomisiones',
            name='aniomes_importacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
